// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mkovacs.reportmanager.domain.report;

import com.mkovacs.reportmanager.domain.report.Application;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Application_Roo_Configurable {
    
    declare @type: Application: @Configurable;
    
}
